services:
  db:
    restart: unless-stopped
    image: "postgres:12.3-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    networks:
      - rengine_network

  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - rengine_network

  celery:
    image: docker.io/talanor/rengine-celery:v0.3
    restart: unless-stopped
    volumes:
      - ./web:/home/rengine/rengine
      - ./scan_results:/home/rengine/scan_results
      # - ./data/github_repos:/usr/src/github
      # - ./data/wordlist:/usr/src/wordlist
      # - ./data/scan_results:/usr/src/scan_results
      # - ./data/gf_patterns:/root/.gf
      # - ./data/nuclei_templates:/root/nuclei-templates
      # - ./data/tool_config:/root/.config
      # - ./data/static_volume:/usr/src/app/staticfiles/
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
      - MIN_CONCURRENCY=${MIN_CONCURRENCY}
    depends_on:
      - db
      - redis
    networks:
      rengine_network:

  celery-beat:
    image: docker.io/talanor/rengine-celery:v0.3
    entrypoint: /home/rengine/rengine/beat-entrypoint.sh
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - celery
    volumes:
      - ./web:/home/rengine/rengine
      # - github_repos:/usr/src/github
      # - wordlist:/usr/src/wordlist
      # - scan_results:/usr/src/scan_results
      # - gf_patterns:/root/.gf
      # - nuclei_templates:/root/nuclei-templates
      # - tool_config:/root/.config
    networks:
      - rengine_network

  web:
    image: docker.io/talanor/rengine-web:v0.2
    restart: unless-stopped
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      # THIS IS A MUST FOR CHECKING UPDATE, EVERYTIME A COMMIT IS MERGED INTO
      # MASTER, UPDATE THIS!!! MAJOR.MINOR.PATCH https://semver.org/
      - RENGINE_CURRENT_VERSION='2.0.5'
    volumes:
      - ./web:/home/rengine/app
      # - ./data/static_volume:/usr/src/app/staticfiles/
      # - ./data/github_repos:/usr/src/github
      # - ./data/wordlist:/usr/src/wordlist
      # - ./data/scan_results:/usr/src/scan_results
      # - ./data/gf_patterns:/root/.gf
      # - ./data/nuclei_templates:/root/nuclei-templates
      # - ./datatool_config:/root/.config
    depends_on:
      - db
      - celery
      - celery-beat
    networks:
      rengine_network:
        aliases:
          - rengine

  proxy:
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
      - web
      - db
      - redis
    secrets:
      - source: proxy.ca
        target: /etc/nginx/certs/rengine_chain.pem
      - source: proxy.cert
        target: /etc/nginx/certs/rengine.pem
      - source: proxy.key
        target: /etc/nginx/certs/rengine_rsa.key
    volumes:
      - ./config/nginx/rengine.conf:/etc/nginx/conf.d/rengine.conf:ro
      - ./web/staticfiles:/usr/src/app/staticfiles/
      - ./scan_results:/usr/src/scan_results
    networks:
      - rengine_network

networks:
  rengine_network:

secrets:
  proxy.ca:
    file: ./secrets/certs/rengine_chain.pem
  proxy.key:
    file: ./secrets/certs/rengine_rsa.key
  proxy.cert:
    file: ./secrets/certs/rengine.pem
