name: ğŸ—ï¸ Build Docker image for pull request

on:
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    name: ğŸ³ Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          # - linux/arm/v7  # Uncomment if you need ARMv7 support
    steps:
      - name: ğŸ“¥ Checkout the git repo
        uses: actions/checkout@v4

      - name: ğŸ–¥ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ·ï¸ Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yogeshojha/rengine
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
            type=sha,prefix=sha-
            type=ref,event=branch
            type=ref,event=pr
      - name: ğŸ—ï¸ Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: web/
          platforms: ${{ matrix.platform }}
          push: false  # Only build, don't push to Docker Hub yet
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ğŸ” Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ğŸ“¤ Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: web/
          platforms: ${{ matrix.platform }}
          push: true  # Push to Docker Hub
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
