name: ğŸš€ Build Docker image

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 */5 * *'

jobs:
  build:
    name: ğŸ³ Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the git repo
        uses: actions/checkout@v4

      - name: ğŸ–¥ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ·ï¸ Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yogeshojha/rengine
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: ğŸ—ï¸ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: web/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max