name: ğŸš€ Build and Push Docker image

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  schedule:
    - cron: '0 0 */5 * *'  # Run every 5 days at midnight UTC

jobs:
  build-and-push:
    name: ğŸ³ Build and Push Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: ğŸ“¥ Checkout the git repo
        uses: actions/checkout@v4

      - name: ğŸ–¥ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ·ï¸ Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yogeshojha/rengine
          tags: |
            type=raw,value=${{ matrix.platform }}-latest,enable={{is_default_branch}}
            type=semver,pattern=${{ matrix.platform }}-{{version}}
            type=semver,pattern=${{ matrix.platform }}-{{major}}.{{minor}}
            type=semver,pattern=${{ matrix.platform }}-{{major}}
            type=sha,prefix=${{ matrix.platform }}-sha-
            type=schedule,pattern=${{ matrix.platform }}-{{date 'YYYYMMDD'}}

      - name: ğŸ—ï¸ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: web/
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max